### ISSUE TITLE
404 not found on about

### ISSUE THREAD

**Issue by nogawb** [info-461-TBD/ShelterConnect#42]
When I am on the home page page I get a 404 file not found error when I click on the about tab in the upper right corner. 

Steps I took:
-Load the page from the initial link
-Click on the about button in the upper right corner. 

<img width="1439" alt="screen shot 2018-06-03 at 5 28 00 pm" src="https://user-images.githubusercontent.com/22626153/40893023-8f36c9ee-6753-11e8-8588-d1149cc68803.png">

**Comment by abegel** [comment]
It works for me.

**Comment by nogawb** [comment]
I just tried it again and its working for me now. It must've been an issue on launch. Do you want me to make another bug report?

**Comment by abegel** [comment]
No, just let the owners close the bug as fixed if they did something to fix it, or worksforme if they didn't?

**Comment by rykerls** [comment]
Hi @nogawb and @abegel,

Thanks for pointing this out. We encountered a hiccup when it came time to deploy to github pages. Our `react-router` configuration was not compatible with gh-pages hosting, so we attempted to fix it before the release deadline. This link did not get updated when we made this change, hence the 404.

This has since been fixed and deployed to: https://info-461-tbd.github.io/ShelterConnect/#/

More information on the bug here: https://github.com/facebook/create-react-app/issues/1765
