### ISSUE TITLE
404 Not Found on Organization Tab

### ISSUE THREAD

**Issue by campbellsean** [info-461-TBD/ShelterConnect#43]
MAJOR ISSUE: From this [link](https://info-461-tbd.github.io/ShelterConnect/#/) I am unable to navigate to the organization tab.

Using Firefox Quantum browser.

I believe this issue is caused because of the way gh-pages works.

![report](https://user-images.githubusercontent.com/24884624/40945266-ea48baae-680c-11e8-8ee2-34480c7a5fc6.jpeg)

Good luck!

**Comment by rykerls** [comment]
Hi @campbellsean,

Thanks for pointing this out. We encountered a hiccup when it came time to deploy to github pages. Our react-router configuration was not compatible with gh-pages hosting, so we attempted to fix it before the release deadline. This link did not get updated when we made this change, hence the 404.

This has since been fixed and deployed to: https://info-461-tbd.github.io/ShelterConnect/#/

More information on the bug here: facebook/create-react-app#1765
