### ISSUE TITLE
All the tabs on the top bar leads to 404 Page Not Found

### ISSUE THREAD

**Issue by Jingwnpn** [info-461-TBD/ShelterConnect#46]

**Comment by rykerls** [comment]
Hi @Jingwnpn 

Thanks for pointing this out. We encountered a hiccup when it came time to deploy to github pages. Our react-router configuration was not compatible with gh-pages hosting, so we attempted to fix it before the release deadline. These links did not get updated when we made this change, hence the 404.

This has since been fixed and deployed to: https://info-461-tbd.github.io/ShelterConnect/#/

More information on the bug here: facebook/create-react-app#1765
