### ISSUE TITLE
Logging in as Null 

### ISSUE THREAD

**Issue by lisakoss** [info-461-TBD/ShelterConnect#54]
When I initially tried to sign up, I inputted an invalid phone number. After I was alerted of this error and fixed it, I submitted my sign up form a second time. Then I received this error:

<img width="1440" alt="screen shot 2018-06-04 at 4 38 29 pm" src="https://user-images.githubusercontent.com/22549728/40947121-e553f92e-6815-11e8-890f-f764152b97a8.png">

Pressing okay didn't redirect me any where and I'm still on the sign up page with zero feedback as to what went wrong. Although, it does appear I was logged in.

[minor]

I submitted this information for all of my fields:
Name: [{Name
Phone number: 5555555555
Email: lisakoss@uw.edu
Address: 111020039430504958439583495834958943 Address
City: 23243334343 Seattle
State: WA 98125
Zip code: 98125
Description: desc
Personal name: Lisa
Personal email: lisakoss@uw.edu
Signature: Lisa

**Comment by sunwookang** [comment]
Hey Lisa,
Thanks for letting us know about this issue! To address the issue, there were two parts to tackle.

1) After closing the alert, you were not redirected to home. We had issues with using browserHistory to push new pages in our application and we were able to correctly fix that issue!

2) The alert was originally supposed to be there in the case that any user that was logged in wanted to sign up for a new account, but it seemed like the alert showed up right after a new user's account was made and right before it pushed to the home page. To fix this, we simply made it so that the registration link in general would be excluded from the header if a user is already logged in.

Thank you for alerting us about this bug!
Sincerely,
Sunwoo Kang
