### ISSUE TITLE
Sign Up Redirection Doesn't Redirect

### ISSUE THREAD

**Issue by lisakoss** [info-461-TBD/ShelterConnect#55]
Once logged in, if I click on the "Register" tab in the navigation bar, an alert pops up saying I'm already logged in. Although, when I click "ok" I am not redirected to the home page of the site. The url in the bar changes from "https://info-461-tbd.github.io/ShelterConnect/#/signup/" to "https://info-461-tbd.github.io/" but I still see the "Sign Up" form. I also get this error in the console from Firebase.

[minor]

<img width="1440" alt="screen shot 2018-06-04 at 4 49 06 pm" src="https://user-images.githubusercontent.com/22549728/40947376-434cec92-6817-11e8-92c1-abab9ea5f2de.png">

**Comment by rykerls** [comment]
@sunwookang I had to fix this issue to fix another that was assigned to me ha. I can handle this one.

**Comment by rykerls** [comment]
Hi @lisakoss,

Thanks for pointing this out. We encountered a hiccup when it came time to deploy to github pages. Our react-router configuration was not compatible with gh-pages hosting, so we attempted to fix it before the release deadline. This link did not get updated when we made this change, hence the error and no redirection, even though you successfully registered.

This has since been fixed and deployed to: https://info-461-tbd.github.io/ShelterConnect/#/

More information on the bug here: facebook/create-react-app#1765
